services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: api 
    restart: unless-stopped
    env_file:
      - ./apps/api/.env
    depends_on:
      - redis
    ports:
      - "5000:5000"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: web
    restart: unless-stopped
    env_file:
      - ./apps/web/.env
    ports:
      - "5173:80"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - web
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
